availableSecrets:
  secretManager:
  - versionName: projects/812611363700/secrets/NEXT_PUBLIC_FIREBASE_CONFIG/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_CONFIG' # This will be an internal Cloud Build environment variable
  - versionName: projects/812611363700/secrets/FIREBASE_CLIENT_EMAIL/versions/latest
    env: 'FIREBASE_CLIENT_EMAIL'
  - versionName: projects/812611363700/secrets/FIREBASE_PRIVATE_KEY/versions/latest
    env: 'FIREBASE_PRIVATE_KEY'

steps:
# Step 1: Deploy the 'calendar' Cloud Function
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies for calendar function'
    args: ['install']
    dir: 'calendar'

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build calendar function'
    args: ['run', 'build']
    dir: 'calendar'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy calendar function'
    dir: 'calendar' # Change directory to 'calendar' before deploying
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          FUNCTION_NAME="calendar"
          API_KEY_SECRET="CALENDAR_API_KEY"
        else
          FUNCTION_NAME="calendar-dev"
          API_KEY_SECRET="CALENDAR_API_KEY_DEV"
        fi

        gcloud functions deploy $$FUNCTION_NAME \
          --entry-point=calendar \
          --runtime=nodejs22 \
          --trigger-http \
          --allow-unauthenticated \
          --source=. \
          --set-secrets=CALENDAR_API_KEY=$$API_KEY_SECRET:latest,GOOGLE_SERVICE_ACCOUNT_CALENDAR_EMAIL=GOOGLE_SERVICE_ACCOUNT_CALENDAR_EMAIL:latest,GOOGLE_PRIVATE_KEY_CALENDAR=GOOGLE_PRIVATE_KEY_CALENDAR:latest

# Step 1: Deploy the 'sms' Cloud Function (existing step)
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies for SMS function'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build SMS function'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy SMS function'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy sms \
          --entry-point=sms \
          --runtime=nodejs22 \
          --trigger-http \
          --allow-unauthenticated \
          --service-account=moonflower-453318@appspot.gserviceaccount.com

 # Step 2: Build and deploy the Next.js web application
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build webapp container image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg "NEXT_PUBLIC_FIREBASE_CONFIG=$${NEXT_PUBLIC_FIREBASE_CONFIG}" \
          --build-arg "NEXT_PUBLIC_FIREBASE_PROJECT_ID=moonflower-453318" \
          --build-arg "FIREBASE_CLIENT_EMAIL=$${FIREBASE_CLIENT_EMAIL}" \
          --build-arg "FIREBASE_PRIVATE_KEY=$${FIREBASE_PRIVATE_KEY}" \
          -t "us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/moab-automation-webapp:$COMMIT_SHA" \
          .
    dir: 'webapp' # Run this step in the webapp directory
    secretEnv: ['NEXT_PUBLIC_FIREBASE_CONFIG','FIREBASE_CLIENT_EMAIL','FIREBASE_PRIVATE_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push webapp container image'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/moab-automation-webapp:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy webapp to Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          SERVICE_NAME="moab-automation-webapp"
          SERVICE_URL="https://moab-automation-webapp-812611363700.us-central1.run.app"
          TWILIO_SID_SECRET="TWILIO_ACCOUNT_SID"
          TWILIO_TOKEN_SECRET="TWILIO_AUTH_TOKEN"
          GOOGLE_SHEET_ID="GOOGLE_SHEET_ID"
          GOOGLE_SERVICE_ACCOUNT_EMAIL="GOOGLE_SERVICE_ACCOUNT_EMAIL"
          GOOGLE_PRIVATE_KEY="GOOGLE_PRIVATE_KEY"
        else
          SERVICE_NAME="moab-automation-webapp-dev"
          SERVICE_URL="https://moab-automation-webapp-dev-812611363700.us-central1.run.app"
          TWILIO_SID_SECRET="TWILIO_ACCOUNT_SID_DEV"
          TWILIO_TOKEN_SECRET="TWILIO_AUTH_TOKEN_DEV"
          GOOGLE_SHEET_ID="GOOGLE_SHEET_ID"
          GOOGLE_SERVICE_ACCOUNT_EMAIL="GOOGLE_SERVICE_ACCOUNT_EMAIL"
          GOOGLE_PRIVATE_KEY="GOOGLE_PRIVATE_KEY"
        fi

        gcloud run deploy $$SERVICE_NAME \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/moab-automation-webapp:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-secrets=TWILIO_ACCOUNT_SID=$$TWILIO_SID_SECRET:latest,TWILIO_AUTH_TOKEN=$$TWILIO_TOKEN_SECRET:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,NEXT_PUBLIC_FIREBASE_CONFIG=NEXT_PUBLIC_FIREBASE_CONFIG:latest,FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest,FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,GOOGLE_SERVICE_ACCOUNT_EMAIL=GOOGLE_SERVICE_ACCOUNT_EMAIL:latest,GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest \
          --set-env-vars=NEXT_PUBLIC_FIREBASE_PROJECT_ID=moonflower-453318,NEXTAUTH_URL=$$SERVICE_URL,NEXT_PUBLIC_URL=$$SERVICE_URL

# Step 3: Build and deploy the lunch cron job
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build cron job container image'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cron'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/lunch-cron:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/lunch-cron:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push cron job container image'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/lunch-cron']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy lunch cron job'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy lunch-cron \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/lunch-cron:$COMMIT_SHA \
          --region=us-central1 \
          --service-account=moonflower-453318@appspot.gserviceaccount.com \
          --set-secrets=GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,GOOGLE_SERVICE_ACCOUNT_EMAIL=GOOGLE_SERVICE_ACCOUNT_EMAIL:latest,GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,TWILIO_PHONE_NUMBER=TWILIO_PHONE_NUMBER:latest

# Tell Cloud Build to push the built image to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/moab-automation-webapp:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/lunch-cron:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
